spring:
  application:
    oj-backend-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: oj-backend-user-service
          uri: lb://oj-backend-user-service
          predicates:
            # 将地址为 /api/user/** 的请求都转发到 lb://oj-backend-user-service、
            # 然后 nacos 会经过负载均衡后转发到具体地址
            - Path=/api/user/**

        - id: oj-backend-question-service
          uri: lb://oj-backend-question-service
          predicates:
            - Path=/api/question/**

        - id: oj-backend-judge-service
          uri: lb://oj-backend-judge-service
          predicates:
            - Path=/api/judge/**

        - id: oj-backend-code-sandbox
          uri: lb://oj-backend-code-sandbox
          predicates:
            - Path=/api/sandbox/**
  main:
    # 网关配置选项
    web-application-type: reactive
server:
  port: 8101

knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
